# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/bauwen/.unreal

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	GameAI_Zombie-Android-DebugGame  \
	GameAI_Zombie-Android-Development  \
	GameAI_Zombie-Android-Shipping  \
	GameAI_Zombie-Linux-DebugGame  \
	GameAI_Zombie-Linux-Development  \
	GameAI_Zombie-Linux-Shipping  \
	GameAI_Zombie-LinuxArm64-DebugGame  \
	GameAI_Zombie-LinuxArm64-Development  \
	GameAI_Zombie-LinuxArm64-Shipping  \
	GameAI_Zombie \
	GameAI_ZombieEditor-Linux-DebugGame  \
	GameAI_ZombieEditor-Linux-Development  \
	GameAI_ZombieEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend GameAI_ZombieEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug GameAI_ZombieEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

GameAI_Zombie-Android-DebugGame:
	 $(BUILD) GameAI_Zombie Android DebugGame  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-Android-Development:
	 $(BUILD) GameAI_Zombie Android Development  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-Android-Shipping:
	 $(BUILD) GameAI_Zombie Android Shipping  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-Linux-DebugGame:
	 $(BUILD) GameAI_Zombie Linux DebugGame  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-Linux-Development:
	 $(BUILD) GameAI_Zombie Linux Development  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-Linux-Shipping:
	 $(BUILD) GameAI_Zombie Linux Shipping  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-LinuxArm64-DebugGame:
	 $(BUILD) GameAI_Zombie LinuxArm64 DebugGame  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-LinuxArm64-Development:
	 $(BUILD) GameAI_Zombie LinuxArm64 Development  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie-LinuxArm64-Shipping:
	 $(BUILD) GameAI_Zombie LinuxArm64 Shipping  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_Zombie: GameAI_Zombie-Linux-Development

GameAI_ZombieEditor-Linux-DebugGame:
	 $(BUILD) GameAI_ZombieEditor Linux DebugGame  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_ZombieEditor-Linux-Development:
	 $(BUILD) GameAI_ZombieEditor Linux Development  -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" $(ARGS)

GameAI_ZombieEditor: GameAI_ZombieEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/bauwen/Documents/Programming/howest/gameai-zombie-BauwenDR/GameAI_Zombie.uproject" -Game 

.PHONY: $(TARGETS)
